# Generated by Django 5.1.2 on 2024-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="dangerous",
            field=models.BooleanField(default=False),
        ),
    ]
